---
title: "first_maps"
author: "Pete"
date: "10/07/2014"
output: html_document
---
This is my attempt to work through a mix of Lincoln's historic mapping tutorial: http://dh-r.lincolnmullen.com/mapping.html 



```{r}
library(rgdal)
library(sp)
library(rgeos)
library(maptools)
library(ggmap)
library(ggplot2)

#load libraries
#First plot
map_sp <- readOGR("nhgis-shp/", "state_1850") 
plot(map_sp, col = "grey")
title("United States, 1850")


#Second plot - Whitney was starting to get a little more into DH at this point.
earth <- readOGR("naturalearth/50m_physical/", "ne_50m_land")
plot(earth, col = "gray"); title("Whitney's Queendom")


#Second plot transformed into a new projection
winkel <- spTransform(earth, CRS("+proj=wintri"))
plot(winkel, col="gray")
title("Whitney's world according to Oswald Winkel")

#Created a list of cities
cities <- data.frame(name = c("Saint Louis, MO", "San Francisco, CA", "Boston, MA", "Charleston, SC", "Houston, TX"), stringsAsFactors=FALSE)

#Gave them a lat/long via ggmap's google map function and binded those fields to my cities DF
cities_geocoded <- geocode(cities$name)
cities <- cbind(cities, cities_geocoded)

#Drew a plot of my cities in space using lat/long and labeled with the "name" column.
ggplot(cities, aes(x=lon, y = lat)) +
  geom_point() + 
  geom_text(aes(label=name), vjust = -1) + 
  coord_map()

#turn the sp into a data frame object.
map_df <- fortify(map_sp, region = "GISJOIN")
#And make a map with ggplot
map_1850 <- ggplot() + 
  geom_map(data = map_df,
           map = map_df, 
  aes(x=long, y=lat, group = group, map_id = id),
  fill = "white",
  color = "black",
  size = 0.2) +
coord_map() +
  theme_minimal()
#Add the "Cities" Data to our 1850 map. Voila!
map_1850 +
  geom_point(data = cities, aes(x = lon, y = lat), color = "red", size = 3) + 
  geom_text(data = cities, aes(x = lon, y = lat, label=name), vjust = -1)



#Now a plot of the Paulist missions on the 1850 map:
#adding new packages
#devtools::install_github("lmullen/historydata")
library(dplyr)
library(historydata)

#adding paulist missions data frame
data(paulist_missions)

#Mapping Paulist missions as points.
map_1850 + 
  geom_point(data = paulist_missions, 
             aes(x=long, y = lat, size = confessions),
             color="red", shape = 1) +
  theme(legend.position="bottom") + 
  scale_size(range = c(2, 8)) + 
  ggtitle("Paulist missions as points")

#Paulist missions with Density instead of points
map_1850 +
  geom_hex(data = paulist_missions, 
           aes(x = long, y = lat)) +
  theme(legend.position = "bottom") +
  ggtitle("Paulist Missions with hex bin")

#Paulist missions with density plot
map_1850 +
  geom_density2d(data = paulist_missions, 
           aes(x = long, y = lat)) +
  theme(legend.position = "bottom") +
  ggtitle("Paulist Missions with density plot")


```


Exploring Chloropleths
```{r}
#Adding Libraries
library(rgdal)
library(sp)
library(rgeos)
library(maptools)
library(ggmap)
library(ggplot2)
library(historydata)
library(dplyr)

#add us county data and farm data
counties_1850_sp <- readOGR("nhgis-shp/", "US_county_1850")
counties_1850_df <- fortify(counties_1850_sp, region ="GISJOIN")
farms_1850 <- read.csv("nhgis0003_csv/nhgis0003_ds11_1850_county.csv", stringsAsFactors = FALSE)
#merge the tables at GISJOIN/ID fields. I had to change the GISJOIN column to id in "farms_1850" to get them to join correctly
colnames(farms_1850)[1]<-"id"
farms_merged <- counties_1850_df %>% 
  left_join(farms_1850, by = "id")
#Plot this map
ggplot(data = farms_merged,
       aes(x = long, y = lat, group = group, fill = AE7001, map_id = id)) +
  geom_map(map = farms_merged) + 
  ggtitle("Average Value of Farms and Buildings in dollars/acre in 1850") +
  coord_map() + 
  theme_minimal() + 
  theme(legend.position = "bottom")
#Explore the farmland values table to improve map. 
summary(farms_1850$AE7001)
ggplot(data = farms_1850, aes (x = AE7001)) + geom_histogram(binwidth = 10) +
  ggtitle("Distribution of farmland values in 1850")
# Break values into bins with classInt package
#install.packages("classInt")
library(classInt)
classIntervals(farms_1850$AE7001, 9, "pretty")
intervals <- classIntervals(farms_1850$AE7001, 9, "jenks")
head(cut(farms_1850$AE7001, breaks = intervals$brks))
#merge it back into our farms dataframe
farms_1850 <- farms_1850 %>%
  mutate(value_classified = cut(AE7001, intervals$brks))
farms_merged <- counties_1850_df %>% 
  left_join(farms_1850, by = "id")
#Now redo the map. Pretty!
ggplot(data = farms_merged,
       aes(x = long, y = lat, group = group, 
           fill = value_classified, map_id = id)) +
  geom_map(map = farms_merged) + 
  ggtitle("Average Value of Farms and Buildings in dollars/acre in 1850") +
  coord_map() + 
  theme_minimal() + 
  theme(legend.position = "bottom")

#Make the map prettier with newer, better colors
#install.packages("RColorBrewer")
library(RColorBrewer)
ggplot(data = farms_merged,
       aes(x = long, y = lat, group = group, fill = value_classified, map_id = id)) +
  geom_map(map = farms_merged, color="gray", size = 0.2) + 
  ggtitle("Average Value of Farms and Buildings in dollars/acre in 1850") +
  coord_map() + 
  theme_minimal() + 
  theme(legend.position = "bottom") +
  scale_fill_brewer(palette = "YlGnBu")

#And limited x/y axis to show only Eastern US, move the legend to the side.
ggplot(data = farms_merged,
       aes(x = long, y = lat, group = group, 
           fill = value_classified, map_id = id)) +
  geom_map(map = farms_merged, color="gray", size = 0.2) + 
  ggtitle("Average Value of Farms and Buildings in dollars/acre in 1850") +
  coord_map() + 
  theme_minimal() + 
  scale_fill_brewer(palette = "YlGnBu") +
  xlim(-98, -65)





```
Now that's a map!